// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlTBKNufvJkQ_q_xmul0d0tiKravJZtsg',
    appId: '1:398639345647:web:34aaf3b68774161239d01a',
    messagingSenderId: '398639345647',
    projectId: 'absensi-mobile-bc8bc',
    authDomain: 'absensi-mobile-bc8bc.firebaseapp.com',
    storageBucket: 'absensi-mobile-bc8bc.appspot.com',
    measurementId: 'G-3M512GQWLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe-q5qOKxClES17dx74cuNPj6L4-KuAfE',
    appId: '1:398639345647:android:0abbd68a3fc7c65f39d01a',
    messagingSenderId: '398639345647',
    projectId: 'absensi-mobile-bc8bc',
    storageBucket: 'absensi-mobile-bc8bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFT6KH2D6q_CziIwhy9nQXSR2_Krnjvcw',
    appId: '1:398639345647:ios:528052184ad0eb9839d01a',
    messagingSenderId: '398639345647',
    projectId: 'absensi-mobile-bc8bc',
    storageBucket: 'absensi-mobile-bc8bc.appspot.com',
    iosBundleId: 'com.example.absensiOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFT6KH2D6q_CziIwhy9nQXSR2_Krnjvcw',
    appId: '1:398639345647:ios:528052184ad0eb9839d01a',
    messagingSenderId: '398639345647',
    projectId: 'absensi-mobile-bc8bc',
    storageBucket: 'absensi-mobile-bc8bc.appspot.com',
    iosBundleId: 'com.example.absensiOnline',
  );
}
